import { HandoffPacket } from './schema.js';

/**
 * Render a handoff packet as a GitHub-ready pull request description.
 */
export function renderPRDescription(packet: HandoffPacket): string {
  const lines: string[] = [];
  const agent = packet.source_agent;

  // Header
  lines.push(`## Summary`);
  lines.push('');
  if (packet.task_state?.goal) {
    lines.push(`**Goal:** ${packet.task_state.goal}`);
    lines.push('');
  }
  if (packet.task_state?.current_step) {
    lines.push(`**Completed:** ${packet.task_state.current_step}`);
    lines.push('');
  }

  // Key files changed
  if (packet.related_files.length > 0) {
    lines.push(`## Files Changed`);
    lines.push('');
    for (const f of packet.related_files.slice(0, 12)) {
      lines.push(`- \`${f}\``);
    }
    if (packet.related_files.length > 12) {
      lines.push(`- _...and ${packet.related_files.length - 12} more_`);
    }
    lines.push('');
  }

  // Decisions
  if (packet.decisions.length > 0) {
    lines.push(`## Design Decisions`);
    lines.push('');
    for (const d of packet.decisions) {
      lines.push(`- **${d.statement}**`);
      if (d.reason) lines.push(`  _Reason: ${d.reason}_`);
    }
    lines.push('');
  }

  // Warnings / known limitations
  if (packet.warnings.length > 0) {
    lines.push(`## Known Limitations / Watch Out`);
    lines.push('');
    for (const w of packet.warnings) {
      lines.push(`- ⚠ ${w.statement}`);
    }
    lines.push('');
  }

  // What was tried and didn't work
  if (packet.failed_attempts.length > 0) {
    lines.push(`## Approaches Rejected`);
    lines.push('');
    for (const f of packet.failed_attempts) {
      lines.push(`- **${f.what}** — ${f.why_failed}`);
      if (f.recommendation) lines.push(`  _Alternative: ${f.recommendation}_`);
    }
    lines.push('');
  }

  // Next steps / open questions
  if (packet.task_state?.next_action || packet.open_questions.length > 0) {
    lines.push(`## Next Steps`);
    lines.push('');
    if (packet.task_state?.next_action) {
      lines.push(`- [ ] ${packet.task_state.next_action}`);
    }
    for (const q of packet.open_questions) {
      lines.push(`- [ ] ${q}`);
    }
    lines.push('');
  }

  // Provenance footer
  lines.push(`---`);
  lines.push(`_Generated by AgentHandoff from \`${agent}\` session context_`);

  return lines.join('\n');
}
